### ISSUE TITLE
Repo address

### ISSUE THREAD

**Issue by trymoto** [panozzaj/vim-copilot-ignore#1]
Hi, Anthony, thanks for sharing your plugin.

I think repo address in `README` (`Plug 'panozzaj/vim-copilot-ignore.vim'`) is outdated and should be without `.vim` suffix.

**Comment by panozzaj** [comment]
I think you are likely right! I don't use Plug myself and ChatGPT generated the documentation. I will tweak this

**Comment by panozzaj** [comment]
Thanks @trymoto!
